require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AccomodationsController do

  # This should return the minimal set of attributes required to create a valid
  # Accomodation. As you add validations to Accomodation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AccomodationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all accomodations as @accomodations" do
      accomodation = Accomodation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:accomodations).should eq([accomodation])
    end
  end

  describe "GET show" do
    it "assigns the requested accomodation as @accomodation" do
      accomodation = Accomodation.create! valid_attributes
      get :show, {:id => accomodation.to_param}, valid_session
      assigns(:accomodation).should eq(accomodation)
    end
  end

  describe "GET new" do
    it "assigns a new accomodation as @accomodation" do
      get :new, {}, valid_session
      assigns(:accomodation).should be_a_new(Accomodation)
    end
  end

  describe "GET edit" do
    it "assigns the requested accomodation as @accomodation" do
      accomodation = Accomodation.create! valid_attributes
      get :edit, {:id => accomodation.to_param}, valid_session
      assigns(:accomodation).should eq(accomodation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Accomodation" do
        expect {
          post :create, {:accomodation => valid_attributes}, valid_session
        }.to change(Accomodation, :count).by(1)
      end

      it "assigns a newly created accomodation as @accomodation" do
        post :create, {:accomodation => valid_attributes}, valid_session
        assigns(:accomodation).should be_a(Accomodation)
        assigns(:accomodation).should be_persisted
      end

      it "redirects to the created accomodation" do
        post :create, {:accomodation => valid_attributes}, valid_session
        response.should redirect_to(Accomodation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved accomodation as @accomodation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Accomodation.any_instance.stub(:save).and_return(false)
        post :create, {:accomodation => { "title" => "invalid value" }}, valid_session
        assigns(:accomodation).should be_a_new(Accomodation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Accomodation.any_instance.stub(:save).and_return(false)
        post :create, {:accomodation => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested accomodation" do
        accomodation = Accomodation.create! valid_attributes
        # Assuming there are no other accomodations in the database, this
        # specifies that the Accomodation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Accomodation.any_instance.should_receive(:update).with({ "title" => "MyText" })
        put :update, {:id => accomodation.to_param, :accomodation => { "title" => "MyText" }}, valid_session
      end

      it "assigns the requested accomodation as @accomodation" do
        accomodation = Accomodation.create! valid_attributes
        put :update, {:id => accomodation.to_param, :accomodation => valid_attributes}, valid_session
        assigns(:accomodation).should eq(accomodation)
      end

      it "redirects to the accomodation" do
        accomodation = Accomodation.create! valid_attributes
        put :update, {:id => accomodation.to_param, :accomodation => valid_attributes}, valid_session
        response.should redirect_to(accomodation)
      end
    end

    describe "with invalid params" do
      it "assigns the accomodation as @accomodation" do
        accomodation = Accomodation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Accomodation.any_instance.stub(:save).and_return(false)
        put :update, {:id => accomodation.to_param, :accomodation => { "title" => "invalid value" }}, valid_session
        assigns(:accomodation).should eq(accomodation)
      end

      it "re-renders the 'edit' template" do
        accomodation = Accomodation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Accomodation.any_instance.stub(:save).and_return(false)
        put :update, {:id => accomodation.to_param, :accomodation => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested accomodation" do
      accomodation = Accomodation.create! valid_attributes
      expect {
        delete :destroy, {:id => accomodation.to_param}, valid_session
      }.to change(Accomodation, :count).by(-1)
    end

    it "redirects to the accomodations list" do
      accomodation = Accomodation.create! valid_attributes
      delete :destroy, {:id => accomodation.to_param}, valid_session
      response.should redirect_to(accomodations_url)
    end
  end

end
